### ISSUE TITLE
accountsBoost overwrites user-provided options

### ISSUE THREAD

**Issue by moltar** [accounts-js/accounts#607]
If I supply my own `db` via `accountsBoost`, it will always get overwritten:

https://github.com/accounts-js/accounts/blob/4e4dc148c41957ddf8021d0b65c476bed668ffa5/packages/boost/src/index.ts#L67

This basically locks `accountsBoost` only to mongo implementation, and will block `@accounts/typeorm`, which is very desirable!

**Comment by pradel** [comment]
You are right this part should be updated to also support typeorm.
Pull request welcome 🙌

**Comment by agustif** [comment]
> You are right this part should be updated to also support typeorm.
> Pull request welcome 🙌

I would love to try to get this done, but would also highly appreciate any guidance on where should I start.

I myself am planning to use AccountsJS with a TypeORM/PostgreSQL project, and was planning to copy the implementation from @brikir/primecms which I got to know about AccountsJS to start from...

**Comment by agustif** [comment]
Well. I don't know about accountsBoost, but I'm gonna go ahead and try to modify one of the examples to use postgresql instead of the default mongo and try to document submit the message as a PR back once it's finished.

Im going to basically follow onto the lines of @birkir on his implementation of this on primecms, which I recently saw made him develop accounts-js/typeorm package which should allow to do this outside of accountsBoost pretty easy than from start!

Hope to be able to do it by myself, will report back soon!

**Comment by agustif** [comment]
I'm a little bit stuck, since I don't know how to create the postgres database (I do create the postgres service with the docker file, might share my progress so far later today either if I succeed or not

**Comment by agustif** [comment]
OMG I don't even believe I got it working by myself, It really needs a lot of polish, and @birkir really deserves all the credit for creating the @accounts/typeorm package.

But it's working!

What would be the best way to commit this back to the community, It really needs some work to become a mergeable PR, but maybe I can just send it as a draft PR on a new branch called examples/graphql-server-typeorm-postgres and recieve some feedback as comments.

Btw I'm also trying to create a new UI version in antd, and would like to end up adding NextJS to the mix, might commit that later down the road!

I'm just so happy I could get it working!! 😄 
<img width="1680" alt="accounts-typeorm-postgres" src="https://user-images.githubusercontent.com/6601142/56158033-3f7d1680-5fc1-11e9-91a3-2d24b0b80753.png">

**Comment by birkir** [comment]
Good to hear @agustif 

You can start by sharing a PR or branch with your changes. We can give you a hand if necessary or feedback.

UI would be great!

**Comment by agustif** [comment]
> Good to hear @agustif
> 
> You can start by sharing a PR or branch with your changes. We can give you a hand if necessary or feedback.
> 
> UI would be great!

OK, cleaning a bit opening a PR soon!

**Comment by agustif** [comment]
Hey @birkir I did start it, but it's really rough on the edges.

https://github.com/accounts-js/accounts/pull/654

I basically copied the implementation from prime-core and adapted it to fit the previous example.

Do you have any feedback on how to proceed? I do really don't know what happened with removing the package lock making tests fail.

Maybe I need to split the two examples in two PR/branches to make this easier to evaluate?

Thanks for helping out, should I open a new Issue about Examples TypeORM/Postgres and leave this issue alone since this is just somewhat orthogonal to the accountsBoost issue.

Thanks again and sorry for the mess!
